### ISSUE TITLE
Simulation good, but gym environment with some problems

### ISSUE THREAD

**Issue by kallilmiguel** [sibyjackgrove/gym-SolarPVDER-environment#1]
Found some errors during an attempt to simulate the environment on gym library.
One of them is when you call a gym.make, and returns an error in the archive PVDER_env.py, saying 
`/content/gym-SolarPVDER-environment/gym_PVDER/envs/PVDER_env.py in __init__(self, n_sim_time_steps_per_env_step, max_sim_time, DISCRETE_REWARD, goals_list, verbosity)
    115         PVDER.count = PVDER.count+1
    116         self.name = 'GymDER_'+ str(self.count)
--> 117         self.initialize_logger()
    118 
    119         self.n_sim_time_steps_per_env_step = n_sim_time_steps_per_env_step

TypeError: initialize_logger() missing 1 required positional argument: 'logging_level' 

To solve this issue, you need to go to put `self.initialize_logger(verbosity)`. But after that, when you try to call env.action_space.sample(), it returns this error: 

  File "/home/kallil/SolarPV-DER-simulation-utility/pvder/dynamic_simulation.py", line 148, in y0
    self.icR_t[-1], self.icI_t[-1], self.xcR_t[-1], self.xcI_t[-1], self.ucR_t[-1],self.ucI_t[-1], self.Vdc_t[-1],self.xDC_t[-1],self.xQ_t[-1],self.xPLL_t[-1],self.wte_t[-1]]

IndexError: too many indices for array` 

Still didn't figure out what to do to solve that one.

**Comment by sibyjackgrove** [comment]
Thank you @kallilmiguel for posting the issue. Yes, this bug is due to some changes that were made in the PV-DER simulation utility and I became aware of it a couple of days ago.  I just pushed a commit  0ff1daebaed9d2a5052f9d812a5a264404f99e1e which should resolve this. Please let me know if this works for you.

**Comment by kallilmiguel** [comment]
All okay now. Thank you very much!!
If I discover any new issue, will warn you shortly.


Kallil Miguel

Acadêmico de Engenharia de Computação

UTFPR Câmpus Pato Branco

________________________________
De: Siby Jose Plathottam <notifications@github.com>
Enviado: terça-feira, 19 de novembro de 2019 15:38
Para: sibyjackgrove/gym-SolarPVDER-environment <gym-SolarPVDER-environment@noreply.github.com>
Cc: kallilmiguel <kallil_cz_miguel@live.com>; Mention <mention@noreply.github.com>
Assunto: Re: [sibyjackgrove/gym-SolarPVDER-environment] Simulation good, but gym environment with some problems (#1)


Thank you @kallilmiguel<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fkallilmiguel&data=02%7C01%7C%7Cec9b58585e844dbf66e408d76d175100%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637097819220796356&sdata=JhPhjbwVKW2fSwEjQvEe6cLsgvhmk7Dy092Z8xSLTqg%3D&reserved=0> for posting the issue. Yes, this bug is due to some changes that were made in the PV-DER simulation utility and I became aware of it a couple of days ago. I just pushed a commit 0ff1dae<https://nam02.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fsibyjackgrove%2Fgym-SolarPVDER-environment%2Fcommit%2F0ff1daebaed9d2a5052f9d812a5a264404f99e1e&data=02%7C01%7C%7Cec9b58585e844dbf66e408d76d175100%7C84df9e7fe9f640afb435aaaaaaaaaaaa%7C1%7C0%7C637097819220806367&sdata=vsNHu18Ral8e8Rgg9xqubtlI%2FwtwUOAAMr5sxg0UqpY%3D&reserved=0> which should resolve this. Please let me know if this works for you.

**Comment by sibyjackgrove** [comment]
Great, thanks for the update. Closing issue.

**Comment by prathamrg** [comment]
Thanks for creating this - its definitely something I'd like to try. But I think there are some compatibility issues with the SolarPV-DER-simulation-utility and this gym environment because when I try to make an environment using `env = gym.make(‘PVDER-v0’)`
I get an error saying, "ImportError: cannot import name 'SolarPV_DER_SinglePhase' from 'pvder.DER_components_single_phase'"
