### ISSUE TITLE
Incompatibility between Simulation Utility and Gym Environment

### ISSUE THREAD

**Issue by prathamrg** [sibyjackgrove/gym-SolarPVDER-environment#2]
Thanks for creating this environment - its definitely something I'm keen to try. But I think there are some compatibility issues between the SolarPV-DER-simulation-utility and this gym environment because when I try to make an environment using `env = gym.make(‘PVDER-v0’)`
I get an error saying, "ImportError: cannot import name 'SolarPV_DER_SinglePhase' from 'pvder.DER_components_single_phase'"

**Comment by prathamrg** [comment]
Note, I've installed both - the simulation utility and the gym environment as instructed:

git clone https://github.com/sibyjackgrove/SolarPV-DER-simulation-utility.git
cd SolarPV-DER-simulation-utility
pip install -e .

cd ../

git clone https://github.com/sibyjackgrove/gym-SolarPVDER-environment.git
cd gym-SolarPVDER-environment
pip install -e .

**Comment by sibyjackgrove** [comment]
@prathamrg  Thank you for the issue and apologies for the delay. This was due to an update I made the pvder package. I have fixed the import paths. Please pull from the repository try it again. Closing the issue. If you still encounter bugs, please feel free to reopen the issue.

**Comment by prathamrg** [comment]
@sibyjackgrove thanks for this. Now I am able to run `env = gym.make(‘PVDER-v0’)` without errors.
However, when I try to reset the environment using `env.reset()` (I am trying the example notebook **gym_PVDER_environment_import_test.ipynb**), I get the following error:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Documents\RL\pvder-test\pvdervenv\lib\site-packages\gym\wrappers\time_limit.py", line 25, in reset
    return self.env.reset(**kwargs)
  File "d:\documents\RL\pvder-test\gym-solarpvder-environment\gym_PVDER\envs\PVDER_env.py", line 328, in reset
    self.setup_PVDER_simulation()
  File "d:\documents\RL\pvder-test\gym-solarpvder-environment\gym_PVDER\envs\PVDER_env.py", line 377, in setup_PVDER_simulation
    PVDER_model = SolarPV_DER_ThreePhase(grid_model = grid_model,events=events,
NameError: name 'SolarPV_DER_ThreePhase' is not defined

As before, I have installed both, the simulation utility and the gym environment as instructed in the documentation.

**Comment by sibyjackgrove** [comment]
@prathamrg sorry for the bug. I have committed some fixes. Can you try again and let me know if it works.

**Comment by prathamrg** [comment]
@sibyjackgrove unfortunately, this gives some new error when I run `env.reset()`:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Documents\RL\pvder-test\pvdervenv\lib\site-packages\gym\wrappers\time_limit.py", line 25, in reset
    return self.env.reset(**kwargs)
  File "d:\documents\RL\pvder-test\gym-solarpvder-environment\gym_PVDER\envs\PVDER_env.py", line 328, in reset
    self.setup_PVDER_simulation()
  File "d:\documents\RL\pvder-test\gym-solarpvder-environment\gym_PVDER\envs\PVDER_env.py", line 380, in setup_PVDER_simulation
    verbosity = self.env_model_spec['verbosity'])
  File "d:\documents\RL\pvder-test\solarpv-der-simulation-utility\pvder\DER_components_three_phase.py", line 58, in __init__
    DER_arguments = self.setup_DER(events,configFile,**kwargs)
  File "d:\documents\RL\pvder-test\solarpv-der-simulation-utility\pvder\DER_components.py", line 52, in setup_DER
    self.parameter_ID = self.get_DER_id(**kwargs)
  File "d:\documents\RL\pvder-test\solarpv-der-simulation-utility\pvder\DER_components.py", line 139, in get_DER_id
    raise ValueError('Neither DER parameter ID nor DER power rating was provided!')
ValueError: Neither DER parameter ID nor DER power rating was provided!

**Comment by sibyjackgrove** [comment]
Ok, It seems I need to make a few more fixes to account for changes in the simulation utility. Will fix it in a couple of days.

**Comment by prathamrg** [comment]
@sibyjackgrove sure, thank you!

**Comment by prathamrg** [comment]
Hello @sibyjackgrove! Any luck with the fixes?

**Comment by sibyjackgrove** [comment]
> Hello @sibyjackgrove! Any luck with the fixes?

@prathamrg  Sorry, haven't been able to get to it. Will try to find some time for it today.

**Comment by prathamrg** [comment]
> > Hello @sibyjackgrove! Any luck with the fixes?
> 
> @prathamrg Sorry, haven't been able to get to it. Will try to find some time for it today.

@sibyjackgrove no worries at all, and thank you!

**Comment by sibyjackgrove** [comment]
@prathamrg Thank you for your patience. I think I have fixed the bug with commit 0f24cc2eac711001d6631c130ddc2a63c0765702.
Please check it out and do let me know if it works.

**Comment by prathamrg** [comment]
@sibyjackgrove It works now, thanks for making the fixes! I will now explore this package further, thanks for all your efforts, much appreciated!

**Comment by sibyjackgrove** [comment]
@prathamrg  You are welcome. Please feel free to open new issues if you encounter any more bugs.
